# Generated by Django 2.2.6 on 2020-02-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=200)),
                ('periodoInicial', models.DateField()),
                ('periodoFinal', models.DateField()),
                ('operacao', models.CharField(max_length=200)),
                ('resultado', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
