# Generated by Django 2.2.6 on 2020-02-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='resultado',
        ),
    ]
