# Generated by Django 2.2.6 on 2020-02-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0002_remove_analise_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='resultado',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
