# Generated by Django 2.2.6 on 2020-02-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0003_analise_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
