# Generated by Django 2.2.6 on 2020-02-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
