# Generated by Django 2.2.6 on 2020-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0005_auto_20200218_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
