# Generated by Django 2.2.6 on 2020-02-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0006_analise_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
