# Generated by Django 2.2.6 on 2020-02-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0007_auto_20200218_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='photo',
        ),
        migrations.AlterField(
            model_name='analise',
            name='resultado',
            field=models.CharField(max_length=200),
        ),
    ]
