# Generated by Django 2.2.6 on 2020-02-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockCalculations', '0008_auto_20200220_0444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
